version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - ./logs/django:/app/logs
    env_file:
      - .env
    build:
      context: .
    command: ["sh", "/entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  redis:
    image: bitnami/redis:7.0
    command: redis-server --requirepass redispassword
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
      - ./logs/redis:/var/log/redis
    env_file:
      - .env
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs/postgres:/var/log/postgresql
    restart: always
    ports:
      - "5432:5432"
  celery-worker:
    build:
      context: .
    command: celery --app worker --loglevel=info --logfile=project/logs/celery.log
    volumes:
      - ./logs/celery:/app/logs
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redispassword@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redispassword@redis:6379/0
    depends_on:
      - django_gunicorn
      - redis
  flower:
    image: mher/flower:2.0
    command: [ 'celery', '--broker=redis://redispassword@redis:6379', 'flower', '--port=5555' ]
    volumes:
      - ./logs/flower:/var/log
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - django_gunicorn
      - celery-worker

volumes:
  static:
  redis_data:
  postgres_data:
